version: "3.8"

services:
  gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    depends_on:
      - invoice-service
      - purchase-order-service
      - receiving-service
      - vendor-service

  invoice-service:
    build: ./invoice-service
    ports:
      - "8083:8080"

  purchase-order-service:
    build: ./purchase-order-service
    ports:
      - "8081:8080"

  receiving-service:
    build: ./receiving-service
    ports:
      - "8082:8080"

  vendor-service:
    build: ./vendor-service
    ports:
      - "8084:8080"
